[theme]
base = "dark"
backgroundColor = "#1a1a19"
secondaryBackgroundColor = "#242422"
primaryColor = "#3987e5"
textColor = "#ffffff"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
